version: '3'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
    command: >
      sh -c "chmod +x /var/www/html/docker/wait-for-it.sh && /var/www/html/docker/wait-for-it.sh db:3306 -- php artisan migrate --force && php artisan db:seed --force && php-fpm"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel_live_score
      MYSQL_USER: tupa
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
